<?php

namespace ReclamationBundle\Repository;

/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function modifier($id,$type,$description,$file){
        $query = $this->getEntityManager()
            ->createQuery(" UPDATE ReclamationBundle:reclamation e SET e.type=:type,e.description=:description,e.fichier=:file where e.id=:id ")
            ->setParameter('id', $id)
            ->setParameter('description', $description)
            ->setParameter('type', $type)
            ->setParameter('file', $file);
        return $query->getResult();
    }

    public function avis($id){
        $query = $this->getEntityManager()
            ->createQuery(" UPDATE ReclamationBundle:reclamation e SET e.avis=:avis where e.id=:id ")
            ->setParameter('id', $id)
            ->setParameter('avis', 1);
        return $query->getResult();
    }

    public function repondre($id,$reponse){
        $query = $this->getEntityManager()
            ->createQuery(" UPDATE ReclamationBundle:reclamation e SET e.reponse=:reponse e.avis=:avis where e.id=:id ")
            ->setParameter('id', $id)
            ->setParameter('reponse',$reponse);
        return $query->getResult();
    }


    public function consulter($id){
        $query = $this->getEntityManager()
            ->createQuery(" SELECT ReclamationBundle:reclamation e where e.id=:id ")
            ->setParameter('id', $id);
        return $query->getResult();
    }
    public function rechercher($texte){
        $query = $this->getEntityManager()
            ->createQuery(" SELECT e from ReclamationBundle:reclamation e JOIN FOSBundle:User u WITH u.id=e.user where u.username LIKE :texte")
            ->setParameter('texte','%'. $texte.'%' );
        return $query->getResult();
    }

    public function DeleteAvis($id){
        $query = $this->getEntityManager()
            ->createQuery("DELETE ReclamationBundle:avis e
      where e.reclamation=:id")->setParameter('id', $id);


        return $query->getResult();
    }
    public function Tri(){

        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(

            "SELECT q  FROM ReclamationBundle:reclamation q order by q.status ASC");
        $result= $query->execute();
        return $result;
    }

    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM ReclamationBundle:reclamation e
                WHERE e.type LIKE :str order by e.status ASC'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function UserName($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT FOSUserBundle:User e
      where e.reclamation=:id")->setParameter('id', $id);

        return $query->getResult();
    }



}
