<?php

namespace PublicationBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function removePublicationCommentaire($idPublication)
    {
        $query = $this->getEntityManager()->createQuery(
            'DELETE PublicationBundle:Commentaire Commentaire
               WHERE Commentaire.Publication_id = :idPublication')
            ->setParameter("idPublication", $idPublication);

        $query->execute();
    }
}
