<?php

namespace PublicationBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHashtag($hashtag)
    {
        $query=$this->getEntityManager()->createQuery("SELECT p FROM PublicationBundle:Publication p where p.catPublication LIKE :hashtag ORDER BY p.datePublication DESC")
            ->setParameter('hashtag', "%" . $hashtag . "%" );
        return $query->getResult();
    }
}
