<?php

namespace PublicationBundle\Repository;

/**
 * ViewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findView($publication_id, $user_id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT v FROM PublicationBundle:Views v where v.Publication_id = :p_id AND v.userId = :u_id")
            ->setParameter('p_id', $publication_id )
            ->setParameter('u_id', $user_id );
        return $query->getResult();
    }
}
