<?php

namespace PublicationBundle\Repository;

/**
 * ViewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewsRepository extends \Doctrine\ORM\EntityRepository
{
}
